#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = -Icppunitlite -Isrc
CFLAGS = -std=c++11 -Wall -fexceptions
RESINC =
LIBDIR =
LIB =
LDFLAGS =

INC_TEST = $(INC)
CFLAGS_TEST = $(CFLAGS) -g
RESINC_TEST = $(RESINC)
RCFLAGS_TEST = $(RCFLAGS)
LIBDIR_TEST = $(LIBDIR) -Lcppunitlite
LIB_TEST = $(LIB)
LDFLAGS_TEST = $(LDFLAGS)
OBJDIR_TEST = obj/test
DEP_TEST =
OUT_TEST = bin/test/calc_test

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/release
DEP_RELEASE =
OUT_RELEASE = bin/release/calc

OBJ_TEST = $(OBJDIR_TEST)/cppunitlite/TestResultDebugOut.o $(OBJDIR_TEST)/main.o $(OBJDIR_TEST)/cppunitlite/TestResultStdErr.o $(OBJDIR_TEST)/cppunitlite/TestResult.o $(OBJDIR_TEST)/cppunitlite/TestRegistry.o $(OBJDIR_TEST)/cppunitlite/Test.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/src/main.o

all: test release

clean: clean_test clean_release

before_test:
	test -d bin/test || mkdir -p bin/test
	test -d $(OBJDIR_TEST)/cppunitlite || mkdir -p $(OBJDIR_TEST)/cppunitlite
	test -d $(OBJDIR_TEST) || mkdir -p $(OBJDIR_TEST)

after_test:
	$(OUT_TEST)

test: before_test out_test after_test

out_test: before_test $(OBJ_TEST) $(DEP_TEST)
	$(LD) $(LIBDIR_TEST) -o $(OUT_TEST) $(OBJ_TEST)  $(LDFLAGS_TEST) $(LIB_TEST)

$(OBJDIR_TEST)/cppunitlite/TestResultDebugOut.o: cppunitlite/TestResultDebugOut.cpp
	$(CXX) $(CFLAGS_TEST) $(INC_TEST) -c cppunitlite/TestResultDebugOut.cpp -o $(OBJDIR_TEST)/cppunitlite/TestResultDebugOut.o

$(OBJDIR_TEST)/main.o: main.cpp
	$(CXX) $(CFLAGS_TEST) $(INC_TEST) -c main.cpp -o $(OBJDIR_TEST)/main.o

$(OBJDIR_TEST)/cppunitlite/TestResultStdErr.o: cppunitlite/TestResultStdErr.cpp
	$(CXX) $(CFLAGS_TEST) $(INC_TEST) -c cppunitlite/TestResultStdErr.cpp -o $(OBJDIR_TEST)/cppunitlite/TestResultStdErr.o

$(OBJDIR_TEST)/cppunitlite/TestResult.o: cppunitlite/TestResult.cpp
	$(CXX) $(CFLAGS_TEST) $(INC_TEST) -c cppunitlite/TestResult.cpp -o $(OBJDIR_TEST)/cppunitlite/TestResult.o

$(OBJDIR_TEST)/cppunitlite/TestRegistry.o: cppunitlite/TestRegistry.cpp
	$(CXX) $(CFLAGS_TEST) $(INC_TEST) -c cppunitlite/TestRegistry.cpp -o $(OBJDIR_TEST)/cppunitlite/TestRegistry.o

$(OBJDIR_TEST)/cppunitlite/Test.o: cppunitlite/Test.cpp
	$(CXX) $(CFLAGS_TEST) $(INC_TEST) -c cppunitlite/Test.cpp -o $(OBJDIR_TEST)/cppunitlite/Test.o

clean_test:
	rm -f $(OBJ_TEST) $(OUT_TEST)
	rm -rf bin/test
	rm -rf $(OBJDIR_TEST)/cppunitlite
	rm -rf $(OBJDIR_TEST)

before_release:
	test -d bin/release || mkdir -p bin/release
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src

after_release:

release: before_release out_release after_release

run: release
	$(OUT_RELEASE)

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/src/main.o: src/main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/main.cpp -o $(OBJDIR_RELEASE)/src/main.o

clean_release:
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/release
	rm -rf $(OBJDIR_RELEASE)/src

.PHONY: before_test after_test clean_test before_release after_release clean_release

